version: "3.9"

services:
  app:
    image: notes-app
    container_name: notes-app
    ports:
      - "8080:8000"
    environment:
      HOST_PORT: 8080
    volumes:
      - ./database:/app/database
      - ./.env:/app/.env
